### ISSUE TITLE
Could you please update the HD performance?

### ISSUE THREAD

**Issue by SmartWB** [282857341/nnFormer#1]
You mentioned to report DSC and HD for Synapse dataset, but there is no HD in Table 2. Could you please update that?

**Comment by 282857341** [comment]
Thanks for your feedback, the hd is as follows:
<img width="567" alt="WeChat Image_20210909130031" src="https://user-images.githubusercontent.com/49048950/132625551-a880e0af-380e-4c3b-8cee-93b600ea6059.png">

**Comment by funnyzhou** [comment]
Thanks for your kind remind. The HD score of nnFormer on Synapse is 11.46. You can reproduce this result using provided codes and models.
