### ISSUE TITLE
questions about the dataset split

### ISSUE THREAD

**Issue by zerone-fg** [282857341/nnFormer#10]
Hello,thank you for the great work,i am just confused about some points below:
1. Do you have the same dataset split as Transunet (e.g. ACDC and Synapse)? because I noticed that this paper directly compared the results from Transunet.
2. Transunet is used for 2d segmentation,and its results were performed on 2d datasets，but it seems that your network is designed for 3d,so why did you directly compare with the 2d result which come from Transunet?
Thank you!

**Comment by 282857341** [comment]
Thansk for your feedback.

1. Synapse's data split is the same as the Transunet. But the author of Transunet did not give the data split of ACDC, so I randomly divided it.
2. TransUNet applies 2D segmentation to 3D datasets.
