### ISSUE TITLE
how to import the weight of natural image pre-training into the model of nnformer

### ISSUE THREAD

**Issue by 834799106** [282857341/nnFormer#11]
Thank you for sharing your work. You mentioned that the weight of natural image pre-training can improve the effect of the model, how can I import the weight of natural image pre-training into the model of nnformer, which I have customized model parameters to train my data?

**Comment by 282857341** [comment]
https://github.com/282857341/nnFormer/blob/3aea3001a918ea2de12ec28cf9043989e99cd8f1/nnformer/training/network_training/nnFormerTrainerV2_ACDC.py#L167-L169

You can replace the code as follows:
xxx.model is your customized model parameters, 
```
checkpoint = torch.load("xxx.model", map_location='cuda')
        for i in checkpoint:
            self.network.state_dict()[i]=checkpoint[i]
        print('I am using the pre_train weight!!')
```
