### ISSUE TITLE
train own data using nnFormer

### ISSUE THREAD

**Issue by Cherryygq** [282857341/nnFormer#12]
大佬您好，感谢开源，我想问问如果使用nnFormer来训练自己的数据，swin transformer的权重文件是必须的吗？我的数据集也是CT片所以我使用了和Synapse类似的change_plan_swim设置和您提供的Synapse预训练权重文件。前面步骤顺利到训练时报错：

File "/home/lab/nnFormer/nnFormer/nnformer/run/run_training.py", line 140, in main
    raise RuntimeError("Could not find trainer class in nnformer.training.network_training")
RuntimeError: Could not find trainer class in nnformer.training.network_training

载入的pkl中很多参数返回都是None，不知道是哪出了问题，期待您的回复，祝好！

**Comment by 282857341** [comment]
有权重文件可以帮助模型进行训练，如果没有的话，只需要注释掉下面的代码
https://github.com/282857341/nnFormer/blob/3aea3001a918ea2de12ec28cf9043989e99cd8f1/nnformer/training/network_training/nnFormerTrainerV2_ACDC.py#L167-L169

关于你出现的这个问题，应该和是程序不能在nnformer.training.network_training这个目录下找到你指令中使用的nnFormerTrainerV2_Synapse，可以检查一下指令是否输错，是否有改动训练器文件的名称和训练器内类的名称

**Comment by Cherryygq** [comment]
谢谢您的解答，我的数据已经成功运行了，但是载入预训练模型的size时出错，关于这个还有几个问题想请教您：
1.预训练模型是通过swimtransformer的swim-small和训练好的model_best.model生成的吗？其他swim模型您有实验过吗
2.我没有使用预训练权重训练完成，测试完成对数据处理后出错:
RuntimeError: The size of tensor a (2) must match the size of tensor b (14) at non-singleton dimension 1
再次感谢！

**Comment by 282857341** [comment]
并没有使用训练好的mode_best.model, 只用了模型第一次保存得到的model_best.model（一般会第二个epoch就会保存），然后我用swin transformer中需要的权重代替我的model_best.model里的权重，你也可以用其他办法，只要能载入swin transformer的权重就好。

Synapse用的是Imagenet-22k swin-l的权重，ACDC用的是ADE-20k swin-s的权重

第二点的问题，不太清楚哪里有问题，你可以检查一下shape

**Comment by Cherryygq** [comment]
您好，我看了get_pretrain_ade.py的载入方法，自行载入swin-l 22K权重后各个层上的relative_position_bias_table 和relative_position_index siz的tensor size与模型以及Synapse中的不匹配，根据window size大小不同计算出来的不同偏执size应该如何匹配呢，理解不当之处请谅解.

**Comment by 282857341** [comment]
对。relative_position_bias_table 和relative_position_index siz不会引入，因为relative_position_bias_table 和relative_position_index siz的size和window size有关，我们改变了window size便不能再用原来的relative_position_bias_table 和relative_position_index size。

如果涉及到因为window size导致size不匹配，我们的方法就是不引入这个权重
