### ISSUE TITLE
Question about splits_final.pkl

### ISSUE THREAD

**Issue by jehovahxu** [282857341/nnFormer#14]
Hi, thank you for the great work.

Following the readme and the below error occurred
![image](https://user-images.githubusercontent.com/18434656/134871457-0a222390-5272-49e5-8ecc-2d13d5b5159f.png)

Can you provide the Splits_final.pkl file?

**Comment by 282857341** [comment]
I have sent the file to your mailbox.

But it stands to reason that running nnunet's preprocessing will automatically generate this file.

**Comment by 282857341** [comment]
Thanks for your feedback，we fix a bug about the data split now.

The change of the data split will not be achieved in the change_plan_swin.py. 

Now, when you run the command
```
nnFormer_train 3d_fullres nnFormerTrainerV2_ACDC 1 0
nnFormer_train 3d_fullres nnFormerTrainerV2_Synapse 2 0  
```
The Splits_final.pkl file will be generated automatically
