### ISSUE TITLE
关于显存问题

### ISSUE THREAD

**Issue by nothingtosay-l** [282857341/nnFormer#15]
您好，感谢您的贡献，我使用了关于Synapse相关配置的文件。nnFormer应该需要比nnunet更大的显存吗？我用RTX3080（10G显存，设备困难）能运行关于nnunet的 bs 为2的3D_fullers。使用nnFormer的时候提示out of memory，修改bs为1后效果特别差不能单纯epoch来弥补。我也尝试着将输入网络大小变小或者注释掉一些计算参数。暂时都没有成功，您能给我一点建议吗（鞠躬）

**Comment by 282857341** [comment]
nnFormer由于计算self-attention的时候会产生一些比较大的中间结果，所以显存占用会比较大。我们没有试过bs=1的情况，可以在缩小网络输入尺寸的同时调整window size，window size对显存的占用的影响也比较大。

**Comment by nothingtosay-l** [comment]
感谢您的快速回复！我修改了输入网络大小[48,96,96]并设置window size为3,我的数据集与Synapse相似，载入您提供的Synapse预训练权重出现了很多mismatch 的尺寸错误，所以我暂时注释了权重文件，发现训练十分不稳定且显存仅占用6/10g，这种情况是不是不太正常呢？还有一个问题就是预训练权重对您的实验结果影响大吗？
祝好！

**Comment by 282857341** [comment]
缩小window size和缩小输入尺寸可以明显减显存占用，而且基于transformer的模型训练确实不如基于cnn的模型稳定。

预训练权重对模型训练有帮助，没有预训练权重结果可能会下降。
