### ISSUE TITLE
about the model_best.model.pkl"

### ISSUE THREAD

**Issue by walynlee** [282857341/nnFormer#16]
Hello, author
When I load the model_best.model.pkl", it occur: RuntimeError: Invalid magic number; corrupt file?
By the way, Could I use the checkpoint as my pretrained model?
Looking forward to your reply. Thanks.

**Comment by 282857341** [comment]
There is no need to load model_best.model.pkl. The true checkpoint is the model_best.model.  What is recorded in the pkl file is the record of the training process.

You can try , but it's not clear if it works.

**Comment by wuliwan** [comment]
> There is no need to load model_best.model.pkl. The true checkpoint is the model_best.model. What is recorded in the pkl file is the record of the training process.
> 
> You can try , but it's not clear if it works.

Get it. Thank you so much.
