### ISSUE TITLE
The comparision with UTNet in ACDC dataset is improper

### ISSUE THREAD

**Issue by yhygao** [282857341/nnFormer#18]
Hi,

I'm the author of UTNet. The Dice score you cite from our paper in the ACDC dataset is wrong. We did experiments in the M&M dataset, not ACDC, so you can't compare them directly. In our experiments on ACDC, UTNet's performance is about 90-93 in dice score on average depends on the split of train/val/test set. Please provide your dataset split such that the comparison is fair.

Thanks

**Comment by 282857341** [comment]
I am sorry for our carelessness, and we will delete the all the experimental results obtained from your paper.

The split of train/val is set in the following code
https://github.com/282857341/nnFormer/blob/84093a8c36d9dad88f1d85d3765899c143e0e99a/nnformer/training/network_training/nnFormerTrainerV2_ACDC.py#L321

And the split of the test can be seen in the
https://github.com/282857341/nnFormer/blob/84093a8c36d9dad88f1d85d3765899c143e0e99a/nnformer/dataset_json/ACDC_dataset.json#L19

**Comment by yhygao** [comment]
Hi,

We've run another experiment on the ACDC dataset using your train/val/test split. The performance of UTNet is as following:

| Methods   | Average    | RV             | Myo         | LV |
| ----------- | ----------- | ----------- | -----------| -----------|
| UTNet       | 91.77       | 90.19         | 89.29        | 95.83 |
| nnFormer | 91.78        | 90.22         | 89.53        | 95.59 |

The UTNet is trained from scratch without any pertaining weight. Please cite the correct performance for fair comparison in your paper.

Thanks
