### ISSUE TITLE
The comparision with UTNet in ACDC dataset is improper

### ISSUE THREAD

**Issue by yhygao** [282857341/nnFormer#19]
Hi,

We've run another experiment on the ACDC dataset using your train/val/test split. The performance of UTNet is as following:

| Methods   | Average    | RV             | Myo         | LV |
| ----------- | ----------- | ----------- | -----------| -----------|
| UTNet       | 91.77       | 90.19         | 89.29        | 95.83 |
| nnFormer | 91.78        | 90.22         | 89.53        | 95.59 |

The UTNet is trained from scratch without any pertaining weight. Please cite the correct performance for fair comparison in your paper.

Thanks

_Originally posted by @yhygao in https://github.com/282857341/nnFormer/issues/18#issuecomment-932578272_

**Comment by funnyzhou** [comment]
Hi Yunhe,

Sorry for our carelessness.

We have removed the results of UTNet and other related baselines reported in your paper from our arxiv version.

On the other hand, there is no need to release the results of UTNet on ACDC in this issue. You should post them in your own paper. BTW, by the time we released nnFormer, we did not see any results of ACDC reported in your paper and also no code is released. If you would like to state that UTNet does display comparable performance on ACDC, please report the numbers in your own paper. Of course, they are after the appearance of nnFormer.

Best,

**Comment by yhygao** [comment]
Thanks for the response. I post the result of UTNet here just in case other researchers to be misled by the improper comparison.
