### ISSUE TITLE
Great work, This code can not train 2D datasets?

### ISSUE THREAD

**Issue by Byronnar** [282857341/nnFormer#2]
Great work, This code can not train 2D datasets?
Thank you.

**Comment by funnyzhou** [comment]
You are right. nnFormer has been optimized for 2D datasets.

But I believe you can modify the architecture by yourself, such as changing 3D conv to 2D conv and adopt 2D Swin Transformer blocks.

**Comment by MengzhangLI** [comment]
If the pipeline follows nnUNet, it can be modified into 2D.

Just (1) Expanding 2D image to psedu 3D, for example, change its shape from (256, 256) to (256, 256, 1) and save it into NIFTI format that nnUNet uses.

(2) Uncomment lines about `plan_3d` [such as here](https://github.com/282857341/nnFormer/blob/e5f8c008441dcdaa33ec9382903aa560ff011beb/nnformer/experiment_planning/nnFormer_plan_and_preprocess.py#L85), thus the plan pipeline would only go through 2D plan.

By the way, I guess performance of 2D nnFormer would not be much better than Swin or Segformer (**2D transformer + existing pretrained model > nnFormer**) becuase the main contribution of nnFormer is bridging the gap between **3D medical image segmentation** and **2D transformer model** in natural image segmentation. The pipeline of many 2D medical images are not way different from natural 2D images, you can have a try to testify my conjunction.

Best,

**Comment by Byronnar** [comment]
> If the pipeline follows nnUNet, it can be modified into 2D.
> 
> Just (1) Expanding 2D image to pseudo 3D, for example, change its shape from (256, 256) to (256, 256, 1) and save it into NIFTI format that nnUNet uses.
> 
> (2) Uncomment lines about `plan_3d` [such as here](https://github.com/282857341/nnFormer/blob/e5f8c008441dcdaa33ec9382903aa560ff011beb/nnformer/experiment_planning/nnFormer_plan_and_preprocess.py#L85), thus the plan pipeline would only go through 2D plan.
> 
> By the way, I guess performance of 2D nnFormer would not be much better than Swin or Segformer (**2D transformer + existing pretrained model > nnFormer**) becuase the main contribution of nnFormer is bridging the gap between **3D medical image segmentation** and **2D transformer model** in natural image segmentation. The pipeline of many 2D medical images are not way different from natural 2D images, you can have a try to testify my conjunction.
> 
> Best,

Thank you so much, I will try.
