### ISSUE TITLE
About ‘val_eval_criterion_MA’

### ISSUE THREAD

**Issue by WaylonLL** [282857341/nnFormer#20]
Hi，
Thank you for your outstanding work.What does 'val_eval_criterion_MA‘ means? And 'Average global foreground Dice' is defined as nnunet?
Best

**Comment by 282857341** [comment]
Average global foreground Dice is the average dice of the validation set of the current epoch.

val_eval_criterion_MA is calculated as follows:
val_eval_criterion_MA[ i ] = 0.9 * val_eval_criterion_MA[i - 1] + 0.1 *  np.mean( Average global foreground Dice[ current epoch ] )
And val_eval_criterion_MA[0] = np.mean( Average global foreground Dice[ first epoch] )
https://github.com/282857341/nnFormer/blob/77c2b6e0c0667b83e17c7d8bd7b67f538ba6fbfe/nnformer/training/network_training/network_trainer.py#L576
