### ISSUE TITLE
The claim and results of the paper are questionable

### ISSUE THREAD

**Issue by rand-rand** [282857341/nnFormer#21]
> Disclaimer: this post is offensive, but I don't want to see academic dishonesty. I would be more than happy if I'm wrong.

The paper claims one of the main contributions is interleaving the transformer layer with the convolutional layer.

However, a `KxKxK Conv with KxKxK stride and C channels` is totally equivalent to `concatenate KxKxK features and then use a linear layer to project to dimension C`. If the 3D case is hard to understand, we can think about the 2D case. a `KxK Conv with KxK stride and C channels` is equivalent to `concatenate KxK features and then use a linear layer to project to dimension C`. The latter one is used in the Swin-Transformer paper with the name `patch merging layer`. 

> To produce a hierarchical representation, the number of tokens is reduced by patch merging layers as the network
gets deeper. The first patch merging layer concatenates the features of each group of 2 × 2 neighboring patches, and
applies a linear layer on the 4C-dimensional concatenated features. (from Swin Transformer paper)

While it is still acceptable that you rename this previous patch merging layer as a so-called convolutional layer (or downsampling layer), how can you achieve 3% better performance with these two equivalent layers as reported in Table 5? 

> Influences of convolutional down-sampling blocks. In Table 5, we report the results of using neighboring concatenation [20] in nnFormer to replace convo- lutional down-sampling blocks. The main operation of neighboring concatenation is to concatenate neighboring patches of features maps in the channel dimension, after which a fully-connected layer is added to reduce the number of channels. From Table 5, we can see that convolutional down-sampling blocks provide over 3 percents improvements over neighboring concatenation in average, demonstrating that applying interleaved convolutional down-sampling blocks are more helpful to build hierarchical object concepts at various scales. (from nnFormer paper)

**Comment by rand-rand** [comment]
See the following code that demonstrates `strided conv` equal to `patch merging`.

```python
import torch
from copy import deepcopy

H = 40
W = 40
Cin = 10
Cout = 20
stride = 2
B = 1 # batch size B = 1
input = torch.rand(B, Cin, H, W) 

###### initialize with same weights ######
conv2d = torch.nn.Conv2d(Cin, Cout, kernel_size=stride, stride=stride)
linear = torch.nn.Linear(Cin * stride * stride, Cout)
print(conv2d.weight.shape, conv2d.bias.shape, linear.weight.shape, linear.bias.shape)
linear.weight.data = conv2d.weight.data.reshape(Cout, Cin, stride * stride).transpose(1, 2).reshape(Cout, Cin * stride * stride)
linear.bias.data = conv2d.bias.data

###### from strided conv ######
output_conv = conv2d(input).view(B, Cout, H * W // stride // stride).transpose(2, 1)
print(output_conv)

###### from patch grouping (code from swin-transformer github) #######
x = input.permute(0, 2, 3, 1)
x0 = x[:, 0::2, 0::2, :]  # B H/2 W/2 Cin
x1 = x[:, 0::2, 1::2, :]  # B H/2 W/2 Cin
x2 = x[:, 1::2, 0::2, :]  # B H/2 W/2 Cin
x3 = x[:, 1::2, 1::2, :]  # B H/2 W/2 Cin
x = torch.cat([x0, x1, x2, x3], -1)  # B H/2 W/2 4*Cin
x = x.view(B, -1, stride * stride * Cin)  # B H/2*W/2 4*Cin
output_linear = linear(x)
print(output_linear)

###### percentage of elements are equal ######
print(((output_linear - output_conv) < 1e-6).float().mean())
```

```
torch.Size([20, 10, 2, 2]) torch.Size([20]) torch.Size([20, 40]) torch.Size([20])
tensor([[[ 0.3247, -0.0705, -0.6484,  ..., -0.1334,  0.1518, -0.0259],
         [ 0.1096, -0.0720, -0.3062,  ...,  0.0836,  0.0532,  0.2092],
         [ 0.1614, -0.0576, -0.3522,  ...,  0.1612,  0.0923,  0.3562],
         ...,
         [-0.0575, -0.0032, -0.5869,  ..., -0.2165,  0.4258,  0.2057],
         [-0.0142, -0.0592, -0.3123,  ...,  0.1105,  0.0470,  0.2470],
         [ 0.5187, -0.0644, -0.4511,  ...,  0.1282,  0.1954, -0.2169]]],
       grad_fn=<TransposeBackward0>)
tensor([[[ 0.3247, -0.0705, -0.6484,  ..., -0.1334,  0.1518, -0.0259],
         [ 0.1096, -0.0720, -0.3062,  ...,  0.0836,  0.0532,  0.2092],
         [ 0.1614, -0.0576, -0.3522,  ...,  0.1612,  0.0923,  0.3562],
         ...,
         [-0.0575, -0.0032, -0.5869,  ..., -0.2165,  0.4258,  0.2057],
         [-0.0142, -0.0592, -0.3123,  ...,  0.1105,  0.0470,  0.2470],
         [ 0.5187, -0.0644, -0.4511,  ...,  0.1282,  0.1954, -0.2169]]],
       grad_fn=<AddBackward0>)
tensor(1.)
```

**Comment by funnyzhou** [comment]
Thanks for pointing it out.

You are right. When the neighborhood size of patch merging and the kernel size of strided conv are the same (with the same stride), both operations are equivalent.

However, when we say convolutional down-sampling, we mean the package of Strided Convolution, LayerNorm layer and GeLU. Actually, in our ablation study, when we replace this package with simple patch merging, the overall performance do greatly drop. Based on our further experiments on it, we found that the GeLU layer plays an important role in the package and we will revise the paper to clarify this phenomenon in the future.

Thanks again for your nice question.

Have a good day.
