### ISSUE TITLE
How to get "splits_final.pkl"

### ISSUE THREAD

**Issue by kosuke-r** [282857341/nnFormer#22]
Hello, Mr.jsguo.

I'm trying your nnFormer, but I am in trouble.
I can't do "change_plan_swin.py", because there is not "splits_final.pkl" in Task001_ACDC and Task002_Synapse folder.
Please tell me how to get this file, or send me this file.

Best regard

**Comment by 282857341** [comment]
> And one more question.
> 
> In the Inference phase, I would like you to tell me correct command line arguments.(I don't know what I put in the -o, -f , -t, and so on.)
> 
> Best regard.
-o is the ouput dir of your inference.
-f is set to 0 by default, you don't need to change this
-t is the task_id 
You can check the meaning of these arguments in the file nnFormer/nnformer/inference/predict_simple.py
