### ISSUE TITLE
How to start preprocess the data

### ISSUE THREAD

**Issue by 55998** [282857341/nnFormer#26]
I have carried out relevant operations according to the README.md, and I have reached the part of preprocess the data. Now, I don't know what to do next, because I got the feedback "nnFormer_convert_decathlon_task: 未找到命令" when I using "nnFormer_convert_decathlon_task -i ../DATASET/nnFormer_raw/nnFormer_raw_data/Task02_Synapse"

so, what command should I enter

**Comment by luoyixi924208423** [comment]
You can input the path ../Task02_Synapse.It can convert data in raw/nnFormer_raw_data automaticly
