### ISSUE TITLE
The model issue

### ISSUE THREAD

**Issue by luoyixi924208423** [282857341/nnFormer#27]
Hello, I would like to ask the following questions: I performed data conversion and preprocessing according to your instructions. When I ran the first fold, line 193 in the model file: assert L == S * H * W reported an error, please ask Have you encountered this problem?

**Comment by 282857341** [comment]
![image](https://user-images.githubusercontent.com/49048950/139999194-9b0f9435-6c65-4a62-85e9-c0378a20a5df.png)
When you start training, make sure that the numbers in the screenshot are the same as yours, if they are different, please use the latest version of the code

**Comment by luoyixi924208423** [comment]
Thanks for the answer，the issue has been solved successfully.The network began to train.

**Comment by 282857341** [comment]
OK
