### ISSUE TITLE
Inference the best model    no such file....

### ISSUE THREAD

**Issue by Jx-Tan** [282857341/nnFormer#28]
when I Evaluating the models in the stage of Tainging/3.Training and Testing the models/A. Use the best model we have trained to infer the test set/(2).Evaluating the models/The Synapse multi-organ CT dataset   Inference
I meet this issue:

(nnFormer) zheng@zheng-PC:~/PycharmProjects/nnFormer-main$ nnFormer_predict -i ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/imagesTs -o ../DATASET/nnFormerr_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output -m 3d_fullres -f 0 -t 2 -chk model_best -tr nnFormerTrainerV2_Synapse

using model stored in  /home/zheng/PycharmProjects/nnFormer-main/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_Synapse_nnFormerPlansv2.1
Traceback (most recent call last):
  File "/home/zheng/anaconda2/envs/nnFormer/bin/nnFormer_predict", line 33, in <module>
    sys.exit(load_entry_point('nnformer', 'console_scripts', 'nnFormer_predict')())
  File "/home/zheng/PycharmProjects/nnFormer-main/nnformer/inference/predict_simple.py", line 224, in main
    shutil.copy(plans_file, join(model_folder_name, "plans.pkl"))
  File "/home/zheng/anaconda2/envs/nnFormer/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/zheng/anaconda2/envs/nnFormer/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zheng/PycharmProjects/nnFormer-main/DATASET/nnFormer_preprocessed/Task002_Synapse/nnFormerPlansv2.1_plans_3D.pkl'

There seems to be no such document here.

I have used the latest code version.

**Comment by 282857341** [comment]
Can you list all the files in this directory？

The file nnFormerPlansv2.1_plans_3D.pkl will be generated after running the command nnFormer_plan_and_preprocess

**Comment by Jx-Tan** [comment]
Thanks, I've solved this problem.

I want to know how to use 2 2080ti to train. And if I use own dataset, is nnFormer_convert_decathlon_task and nnFormer_plan_and_preprocess required.

**Comment by 282857341** [comment]
Training with two GPUs is a bit complicated, when inference.
 I have uploaded the file right now to train with the multi gpus
nnformer/training/network_training/nnFormerTrainerV2_DDP_ACDC.py

The training commands is 
~~~
CUDA_VISIBLE_DEVICES=0,1,2... python -m torch.distributed.launch --master_port=XXXX --nproc_per_node=Y run/run_training_DDP.py 3d_fullres nnFormerTrainerV2_DDP_ACDC TASK_NAME_OR_ID FOLD --dbs
~~~
the detail can be seen in the DDP_training in [nn-UNet](https://github.com/MIC-DKFZ/nnUNet#multi-gpu-training).

things to do before you begin the inference.
~~~
1.Delete the DDP_ characters of the training folder, such as nnFormerTrainerV2_DDP_ACDC__nnFormerPlansv2.1->nnFormerTrainerV2_ACDC__nnFormerPlansv2.1
2.nnFormer_change_trainer_class -i ./nnFormerTrainerV2_ACDC__nnFormerPlansv2.1 -tr nnFormerTrainerV2_ACDC__nnFormerPlansv2.1
~~~

**Comment by 282857341** [comment]
yes, if you ues your own data ,nnFormer_convert_decathlon_task and nnFormer_plan_and_preprocess are required.

**Comment by Jx-Tan** [comment]
thank you so much!

Where can I set the number of epochs？And, with one GPU, each epoch will take 160 seconds average. Is this speed normal?
