### ISSUE TITLE
Task056  Task083_Verse参数设置

### ISSUE THREAD

**Issue by yangshunDragon** [282857341/nnFormer#3]
大神你好， 感谢开源！你们的算法表现很惊艳，赞！我们想试试nnFormer在Verse数据上的表现。但是没太看明白你们change_plan_swin.py脚本里面的参数具体是怎么设置？Task001_ACDC和Task002_Synapse的配置有些区别， 如果换成VerSe数据集， 建议怎么修改配置参数？还需要多改动哪些地方？ 另外一点，论文里面提到”V-MSA模块，让计算复杂度减少了超过98%“，那么平均推理速度相对nnUnet大概达到多少呢？

**Comment by 282857341** [comment]
不好意思，之前忘记了回复。

'patch_size'设置为你输入网络的数据大小。‘pool_op_kernel_sizes’的话，你在哪层进行了下采样就把该层的该维度的数字设置为2，比如task001第一次下采样只对h、w维度下采样，d维度没有变化，所以第一层的数字设置为[1,2,2]。’conv_kernel_sizes’和我们保持一样就好。

由于nnunet框架从训练集文件夹里划分出验证集，就要像task001_Synapse那样对splits_final进行修改。

由于transformer对shape比较敏感，你需要计算一下输入网络的数据最后一次下采样后的shape，将这个shape设置为window size。修改in_chans为你的输入模态数，修改final_patch_expanding函数中的输出通道数。修改pretrain_img_size为你的crop size大小。如果你的网络每一层下采样都固定是2的话，参考synapse网络。如果你的网络某一层某个维度没有进行下采样，参考acdc网络。

由于acdc网络每一层下采样的幅度不是固定的，你需要设置acdc网络中的BasicLayer和BasicLayer_up中input_resolution参数

推理速度的话没有具体比较过。

**Comment by 282857341** [comment]
如果需要改变网络结构的话，还需要对Pretrained_weight文件夹里的预训练模型进行修改

**Comment by yangshunDragon** [comment]
> 如果需要改变网络结构的话，还需要对Pretrained_weight文件夹里的预训练模型进行修改

多谢您的回复。 请问具体是如何修改的？有相关的原始权重文件和对应脚本吗， 我们发现Task001_ACDC和Task002_Synapse这2个任务提供的预训练模型大小不一样

**Comment by yangshunDragon** [comment]
> 如果需要改变网络结构的话，还需要对Pretrained_weight文件夹里的预训练模型进行修改

多谢您的回复。 请问具体是如何修改的？有相关的原始权重文件和对应脚本吗， 我们发现Task001_ACDC和Task002_Synapse这2个任务提供的预训练模型大小不一样

**Comment by 282857341** [comment]
获取预训练权重的文件放在 get_pretrain_ade.py里了，原始的权重文件就是swin transformer的权重文件。

**Comment by yangshunDragon** [comment]
> 推理速度的话没有具体比较过

我测试了一下速度。ACDC数据集（数据大小~0.6MB，模型大小 260MB），推理速度平均1.94s/it ;  Synapse数据集（数据大小~33MB，模型大小1.1GB），平均速度159.5s/it. Verse数据基本都是大于30MB的，所以速度上可能和nnUnet有点类似。速度是nnUnet的一个劣势。如果nnFormer++能做到兼顾精度和速度就很赞了

**Comment by spinemumu** [comment]
> 感谢开源！你们的算法表现很惊艳，赞！我们想试试nnFormer在Verse数据上的表现。但是没太看明白你们change_plan_swin.py脚本里面的参数具体是怎么设置？Task001_ACDC和Task002_Synapse的配置有些区别， 如果换成VerSe数据集， 建议怎么修改配置参数？还需要多改动哪些地方？ 另外一点，论文里面提到”V-MSA模块，让计算复杂度减少了超过98%“，那么平均推理速度相对nnUnet大概达到多少呢？

Hello, have you run through the Verse dataset with nnformer yet? I also want to try replicating the Verse dataset with nnformer recently. If you succeed, can you guide the process? Looking forward to your reply, thank you.

**Comment by spinemumu** [comment]
> > 感谢开源！你们的算法表现很惊艳，赞！我们想试试nnFormer在Verse数据上的表现。但是没太看明白你们change_plan_swin.py脚本里面的参数具体是怎么设置？Task001_ACDC和Task002_Synapse的配置有些区别， 如果换成VerSe数据集， 建议怎么修改配置参数？还需要多改动哪些地方？ 另外一点，论文里面提到”V-MSA模块，让计算复杂度减少了超过98%“，那么平均推理速度相对nnUnet大概达到多少呢？
> 
> Hello, have you run through the Verse dataset with nnformer yet? I also want to try replicating the Verse dataset with nnformer recently. If you succeed, can you guide the process? Looking forward to your reply, thank you.



> > 如果需要改变网络结构的话，还需要对Pretrained_weight文件夹里的预训练模型进行修改
> 
> 多谢您的回复。 请问具体是如何修改的？有相关的原始权重文件和对应脚本吗， 我们发现Task001_ACDC和Task002_Synapse这2个任务提供的预训练模型大小不一样

您好，想问下您是否已经解决了用nnformer训练verse数据集的问题，想请教您该如何跑通，很期待与您取得联系，希望收到您的回复，我的qq邮箱是1062183203@qq.com，谢谢
