### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by Jx-Tan** [282857341/nnFormer#30]
Thanks for your work!

I want to know if I use my own dataset which is 3D nii.gz of abdomen, is need also to use nnFormer_convert_decathlon_task and nnFormer_plan_and_preprocess? I see the documention of two command in nnUnet, it seem to convert the MSD(4D) to 3D, I'm not sure what that means, if my own data is 3D, need I use these two command again?

**Comment by 282857341** [comment]
if your Data is 3D, nnFormer_convert_decathlon_task will only change the folder name and file name
And nnFormer_plan_and_preprocess is required at any time.

**Comment by Jx-Tan** [comment]
Thanks.

The main function of command nnFormer_plan_and_preprocess is?

**Comment by 282857341** [comment]
crop, resample and normalize the data

**Comment by Jx-Tan** [comment]
Thans for your reply
