### ISSUE TITLE
problrm with Multi-GPUS training

### ISSUE THREAD

**Issue by Jx-Tan** [282857341/nnFormer#31]
I see the method of training with Multi-GPUS, the upload file is nnFormerTrainerV2_DDP_ACDC.py. My problem is this file is only training with ACDC dataset? Or it also used in Synapse dataset or other dataset without changes?

**Comment by Jx-Tan** [comment]
And one more question. If I use my own dataset instead the Synapse dataset, and with same Network Architecture the SWIN-UNET, which networkTrainer file I should used? Can I use the nnFormerTrainerV2_Synapse.py? Is it need changes?

Thanks.

**Comment by 282857341** [comment]
1.Just change all the ‘ACDC’ to ‘Synapse’ in the nnFormerTrainerV2_DDP_ACDC.py and nnFormerTrainerV2_ACDC.py .
2.You can use nnFormerTrainerV2_Synapse.py , just need to change the network architecture that you import in the trainer, and it's best to name the trainer and the file with a new name

**Comment by 282857341** [comment]
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/training/network_training/nnFormerTrainerV2_ACDC.py#L25
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/training/network_training/nnFormerTrainerV2_ACDC.py#L40
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/training/network_training/nnFormerTrainerV2_DDP_ACDC.py#L24
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/training/network_training/nnFormerTrainerV2_DDP_ACDC.py#L37

All changes you need to make is here. Don't forget rename the file name, file name should be same with the class name
