### ISSUE TITLE
problem of pretrained weight and network architecture

### ISSUE THREAD

**Issue by Jx-Tan** [282857341/nnFormer#35]
I change the nnformer architecture in UP stage of swintransformerblock.
The detail of changes is :
![740EDD944AFC5EE22745D1809996F21D](https://user-images.githubusercontent.com/52224876/141670607-b85b187c-c8c6-4789-b72d-353ce05e1d70.jpg)
I am written the class of SwinTransformerBlockUp, it different from SwinTransformerBlock in forward.
But I get this Error:
![C6F08B1F957590041F0B86F72C62B124](https://user-images.githubusercontent.com/52224876/141670681-7111d349-aaad-4099-afc0-edf631755f06.jpg)
This seems to be caused by checkpoint of pretrain_Synapse.model
![5AB9D26C6E672DAC5684E1722C368E5C](https://user-images.githubusercontent.com/52224876/141670731-994dec24-a8b8-43aa-8473-eb8860f92c0e.jpg)

Can I train without using the pre training model? What changes do I need.

And, the command I used is 3d_fullres nnFormerTrainerV2_Synapse 2 0.

Thans.

**Comment by 282857341** [comment]
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/training/network_training/nnFormerTrainerV2_Synapse.py#L167-L169
You can delete this part of the code

**Comment by Jx-Tan** [comment]
Thanks!
I can run it.
