### ISSUE TITLE
About the input data shape and the data shape before network

### ISSUE THREAD

**Issue by Jx-Tan** [282857341/nnFormer#37]
Thanks for your working.

I see the dataset(Synapse) shape is slice×512×512, and with the process of load data, the shape is change to slice×457×457, I can understand this change which is adjust the spacing of 'X' and 'Y'. But before the data send to the network, I see the shape is changed to (2, 1, 64, 128, 128), I can understand some dim mean--(Batch, modality, slice, H, W), maybe I didn't understand it correctly, my question is: 
① How to change the shape from slice×457×457 to 64, 128, 128, is it automatic?
② Is the shape accepted by the network must be (2, 1, 64, 128, 128)?
③ If I have other data whice shape is also slice×512×512 but not the abdomen CT(for example, the lungs), is it automatic change to the shape of (2, 1, 64, 128, 128) with the process of training?
④ If I have other data whice shape is not slice×512×512 (for example, 24×320×320), is it automatic change to the shape of (2, 1, 64, 128, 128) before send to the network? And, If not, how to change the shape(such 24×320×320) to fit the network?

Thanks.

**Comment by 282857341** [comment]
1.64, 128, 128 is the crop sizes, which are random cropped from the complete data size（slice×457×457） each time the data is loaded.
You can set the set the data here, and you can set the shape as you want, for every time you load the single data, If the size of the data is not large enough to be cropped, it will pad the data.(for example the crop size is 64,128,128, but the image shape is 50,457,457, we will pad the size of 50), 

https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/run/default_configuration.py#L60
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/network_architecture/Swin_Unet_l_gelunorm.py#L922-L923
