### ISSUE TITLE
print tensor size in iterations

### ISSUE THREAD

**Issue by tangzhe0220** [282857341/nnFormer#38]
When I call: CUDA_VISIBLE_DEVICES=0 nnFormer_train 3d_fullres nnFormerTrainerV2 1 0
the program always prints tensor size during each iteration.

How shall I fix this?

![image](https://user-images.githubusercontent.com/20511588/143022350-c973a5a2-5869-4bd8-97f2-aedfc93d1986.png)

**Comment by 282857341** [comment]
https://github.com/282857341/nnFormer/blob/9e992aae4a054f19fadef8d91cf26a4ff27d5c32/nnformer/network_architecture/generic_UNet.py#L389

I delete the print(x.shape) in the code now.
By the way, the code you are running is not the nnformer's network but nnunet's
You should use command like
CUDA_VISIBLE_DEVICES=0 nnFormer_train 3d_fullres nnFormerTrainerV2_ACDC 1 0
