### ISSUE TITLE
Why all test samples appear in training dataset for Synapse? 

### ISSUE THREAD

**Issue by SmartWB** [282857341/nnFormer#4]
Hello, 
In the paper, it is mentioned that "18 cases are extracted to build the training set while the rest 12 cases are used for testing". However, in your released json file ('/nnformer/dataset_json/Synapse.json'), why all test samples appear in training part? And the "numTraining" is also set to 30. 

Is there a mistake in the process？
![1631196719(1)](https://user-images.githubusercontent.com/22838949/132701966-dd0c002f-3104-4bd9-9abd-ff59d1a26070.png)

**Comment by 282857341** [comment]
Thanks for your feedback, The numTraining and numTest in the Synapse.json is just to cater for the nnunet's framework, and the actual numTraining and numTest is still 18 and 12. There are no mistakes. 

And you can see the "description" in the Synapse.json : "It seems that we use the whole data to train, but we will change numTraining when you running the change_plan_swin.py"
