### ISSUE TITLE
ACDC best model-weight only reach mean DSC of 89.97

### ISSUE THREAD

**Issue by savinienb** [282857341/nnFormer#52]
Hello,

I tried to run the provided fully trained nnFormer model's weight with both the code from December and the latest version of the code and could not reproduce the paper results (89.97 mean dice against 91.78; same scores as https://github.com/282857341/nnFormer/issues/25)

It seems that the inference run on the raw data rather than the pre-processed one, could this be the issue ?

Thanks !

**Comment by 282857341** [comment]
Sorry, we uploaded a wrong checkpoint, but the real checkpoint was not saved, so I uploaded the checkpoint of the last epoch of the training process, and the dice is 91.87.  You can directly replace the original checkpoint
