### ISSUE TITLE
Predict error

### ISSUE THREAD

**Issue by aubest** [282857341/nnFormer#55]
进行预测的时候会出现问题，卡住不动 
(nnFormer) ay@dgx-station:/home/ay/nnFormer/DATASET/nnFormer_raw/nnFormer_raw_data/nnFormer_raw_data/Task002_Synapse$ nnFormer_predict -i imagesTs -o inferTs/nnformer_synapse -m 3d_fullres -t 2 -f 0 -chk model_best -tr nnFormerTrainerV2_nnformer_synapse
using model stored in  /home/ay/nnUNet/nnUNet_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_nnformer_synapse__nnFormerPlansv2.1
This model expects 1 input modalities for each image
Found 12 unique case ids, here are some examples: ['img0032' 'img0029' 'img0035' 'img0036' 'img0003' 'img0036' 'img0002'
 'img0001' 'img0001' 'img0001']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 12
number of cases that still need to be predicted: 12
emptying cuda cache
loading parameters for folds, [0]
2022-02-26 10:35:38.218333: Using dummy2d data augmentation
[0.57142857 0.28571429 0.14285714]
using the following model files:  ['/home/ay/nnUNet/nnUNet_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_nnformer_synapse__nnFormerPlansv2.1/fold_0/model_best.model']
starting preprocessing generator
starting prediction...
preprocessing inferTs/nnformer_synapse/img0001.nii.gz
using preprocessor GenericPreprocessor
preprocessing inferTs/nnformer_synapse/img0002.nii.gz
using preprocessor GenericPreprocessor
preprocessing inferTs/nnformer_synapse/img0003.nii.gz
using preprocessor GenericPreprocessor
preprocessing inferTs/nnformer_synapse/img0004.nii.gz
using preprocessor GenericPreprocessor
preprocessing inferTs/nnformer_synapse/img0008.nii.gz
using preprocessor GenericPreprocessor
preprocessing inferTs/nnformer_synapse/img0022.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 89, 512, 512) after crop: (1, 89, 512, 512) spacing: [5.         0.76757801 0.76757801]

separate z, order in z is 0 order inplane is 3
before crop: (1, 139, 512, 512) after crop: (1, 139, 512, 512) spacing: [3.         0.72070312 0.72070312]

before crop: (1, 147, 512, 512) after crop: (1, 147, 512, 512) spacing: [3.         0.66796875 0.66796875]

before crop: (1, 140, 512, 512) after crop: (1, 140, 512, 512) spacing: [3.      0.59375 0.59375]

before crop: (1, 148, 512, 512) after crop: (1, 148, 512, 512) spacing: [3.         0.72851562 0.72851562]

separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
before crop: (1, 198, 512, 512) after crop: (1, 198, 512, 512) spacing: [3.        0.8984375 0.8984375]

separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 1
separate z, order in z is 0 order inplane is 1
separate z, order in z is 0 order inplane is 1
separate z, order in z is 0 order inplane is 1
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([3.     , 0.59375, 0.59375]), 'spacing_transposed': array([3.     , 0.59375, 0.59375]), 'data.shape (data is transposed)': (1, 140, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 140, 401, 401)}

(1, 140, 401, 401)
preprocessing inferTs/nnformer_synapse/img0035.nii.gz
using preprocessor GenericPreprocessor
predicting inferTs/nnformer_synapse/img0004.nii.gz
I am here !!!
before: {'spacing': array([3.        , 0.72070312, 0.72070312]), 'spacing_transposed': array([3.        , 0.72070312, 0.72070312]), 'data.shape (data is transposed)': (1, 139, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 139, 487, 487)}

True
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 140, 401, 401)
patch size: [ 64 128 128]
steps (x, y, and z): [[0, 25, 51, 76], [0, 55, 109, 164, 218, 273], [0, 55, 109, 164, 218, 273]]
number of tiles: 144
computing Gaussian
(1, 139, 487, 487)
preprocessing inferTs/nnformer_synapse/img0029.nii.gz
Traceback (most recent call last):
  File "/home/ay/.conda/envs/nnFormer/bin/nnFormer_predict", line 33, in <module>
    sys.exit(load_entry_point('nnformer', 'console_scripts', 'nnFormer_predict')())
  File "/raid/user_dir/ay/nnFormer/nnformer/inference/predict_simple.py", line 229, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/raid/user_dir/ay/nnFormer/nnformer/inference/predict.py", line 637, in predict_from_folder
    segmentation_export_kwargs=segmentation_export_kwargs)
  File "/raid/user_dir/ay/nnFormer/nnformer/inference/predict.py", line 221, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "/raid/user_dir/ay/nnFormer/nnformer/training/network_training/nnFormerTrainerV2_nnformer_synapse.py", line 245, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/raid/user_dir/ay/nnFormer/nnformer/training/network_training/nnFormerTrainer_synapse.py", line 524, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/raid/user_dir/ay/nnFormer/nnformer/network_architecture/neural_network.py", line 150, in predict_3D
    verbose=verbose)
  File "/raid/user_dir/ay/nnFormer/nnformer/network_architecture/neural_network.py", line 387, in _internal_predict_3D_3Dconv_tiled
    gaussian_importance_map)[0]
  File "/raid/user_dir/ay/nnFormer/nnformer/network_architecture/neural_network.py", line 524, in _internal_maybe_mirror_and_pred_3D
    pred = self.inference_apply_nonlin(self(x))
  File "/home/ay/.conda/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/raid/user_dir/ay/nnFormer/nnformer/network_architecture/nnFormer_synapse.py", line 953, in forward
    seg_outputs=self.final(out[-1])
  File "/home/ay/.conda/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 1 positional argument but 2 were given
using preprocessor GenericPreprocessor
before: {'spacing': array([3.        , 0.72851562, 0.72851562]), 'spacing_transposed': array([3.        , 0.72851562, 0.72851562]), 'data.shape (data is transposed)': (1, 148, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 148, 492, 492)}

before: {'spacing': array([3.        , 0.66796875, 0.66796875]), 'spacing_transposed': array([3.        , 0.66796875, 0.66796875]), 'data.shape (data is transposed)': (1, 147, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 147, 451, 451)}

(1, 148, 492, 492)
before crop: (1, 94, 512, 512) after crop: (1, 94, 512, 512) spacing: [5.         0.91992199 0.91992199]

(1, 147, 451, 451)
separate z, order in z is 0 order inplane is 3
before crop: (1, 100, 512, 512) after crop: (1, 100, 512, 512) spacing: [3.    0.875 0.875]

separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([5.        , 0.76757801, 0.76757801]), 'spacing_transposed': array([5.        , 0.76757801, 0.76757801]), 'data.shape (data is transposed)': (1, 89, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 148, 519, 519)}

(1, 148, 519, 519)
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([3.       , 0.8984375, 0.8984375]), 'spacing_transposed': array([3.       , 0.8984375, 0.8984375]), 'data.shape (data is transposed)': (1, 198, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 198, 607, 607)}

(1, 198, 607, 607)
before: {'spacing': array([3.   , 0.875, 0.875]), 'spacing_transposed': array([3.   , 0.875, 0.875]), 'data.shape (data is transposed)': (1, 100, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 100, 591, 591)}

(1, 100, 591, 591)
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([5.        , 0.91992199, 0.91992199]), 'spacing_transposed': array([5.        , 0.91992199, 0.91992199]), 'data.shape (data is transposed)': (1, 94, 512, 512)}
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 157, 622, 622)}

(1, 157, 622, 622)

**Comment by 282857341** [comment]
我修改了网络结构文件，现在predict的时候不会出现这个问题。这主要是因为predict的时候把用于deep supervision的低分辨率图像也返回了的原因

**Comment by aubest** [comment]
谢谢 问题确实解决了
