### ISSUE TITLE
测试错误

### ISSUE THREAD

**Issue by lushanfu** [282857341/nnFormer#64]
你好，请问训练正常，测试时候直接报显存不足，显卡24G。原图为 172x512x512  patchsize=64x128x128   [仅测试了一个case.]
![ae5319072019691e2d917d8b5319b1e](https://user-images.githubusercontent.com/31736424/164185849-5f366f34-b516-4107-8363-18270cbe037e.png)

**Comment by lushanfu** [comment]
我使用了predictsimple.py  ,在这段代码中，每预测一个patch后，显存就扩大一些，不断增长。
![image](https://user-images.githubusercontent.com/31736424/164188512-66725609-4202-46d8-8963-31e7ad55ccb2.png)

**Comment by 282857341** [comment]
这个问题比较少见，我也不太清楚具体问题在哪里。这个大小的patch应该不会造成显存的溢出，可以试一下将num_threads_preprocessing和num_threads_nifti_save这两个参数减小

**Comment by lushanfu** [comment]
好的，谢谢。我尝试把前向推理中的变量 del   都没效果，也把多线程关了也没法释放显存。

**Comment by 282857341** [comment]
不知道这个方法有没有用，那就是测试的时候把with torch.no_grad():注释掉。虽然这样做有违直觉，但是我用这个框架做2d的模型的训练时遇到了内存占用不断扩大的问题，注释掉with torch.no_grad():就没问题了。

或者试一下更新一下pytorch版本，我问了nnunet的作者这个现象的原因，他说是pytorch版本的问题
```https://github.com/MIC-DKFZ/nnUNet/issues/904```

**Comment by lushanfu** [comment]
> 不知道这个方法有没有用，那就是测试的时候把with torch.no_grad():注释掉。虽然这样做有违直觉，但是我用这个框架做2d的模型的训练时遇到了内存占用不断扩大的问题，注释掉with torch.no_grad():就没问题了。
> 
> 或者试一下更新一下pytorch版本，我问了nnunet的作者这个现象的原因，他说是pytorch版本的问题 `https://github.com/MIC-DKFZ/nnUNet/issues/904`

谢谢您。
