### ISSUE TITLE
AssertionError: input feature has wrong size

### ISSUE THREAD

**Issue by CarolRen233** [282857341/nnFormer#7]
大佬您好！我在训练ACDC的时候，出现了“assert L == S * H * W, "input feature has wrong size ，AssertionError: input feature has wrong size”

B, L, C： 4 50176 96
S, H, W : 14 40 40
S * H * W: 22400

整个过程完全按照你的代码复现，请问是哪里出问题了吗？

**Comment by puppy2000** [comment]
> 大佬您好！我在训练ACDC的时候，出现了“assert L == S * H * W, "input feature has wrong size ，AssertionError: input feature has wrong size”
> 
> B, L, C： 4 50176 96 S, H, W : 14 40 40 S * H * W: 22400
> 
> 整个过程完全按照你的代码复现，请问是哪里出问题了吗？
你发现问题在哪里了吗？我遇到同样的问题
