### ISSUE TITLE
pretrained model for synapse

### ISSUE THREAD

**Issue by hellopipu** [282857341/nnFormer#70]
Hi, can you provide the pre-trained model `gelunorm_former_skip_global_shift.model` ? Thanks.

**Comment by 282857341** [comment]
The pre-trained weights are already in the google drive link

**Comment by hellopipu** [comment]
Yes, I found 2 pretrained models in the link, since the name is inconsistent with the code [here](https://github.com/282857341/nnFormer/blob/02981008c99c7be6fad004f6a0b9e237d6985707/nnformer/training/network_training/nnFormerTrainerV2_nnformer_synapse.py#L177), I guess `synapse_pretrain.model` seems to be what I need , but it doesn't load correctly.
