### ISSUE TITLE
关于网络配置文件nnFormerPlansv2.1_plans_3D.pkl

### ISSUE THREAD

**Issue by lzy-whut** [282857341/nnFormer#73]
您好，我使用您的代码预处理后得到的nnFormerPlansv2.1_plans_3D.pkl文件和nnunet预处理后相同的，直接使用导致错误如下：
![image](https://user-images.githubusercontent.com/58968914/170454783-cec0e096-92a2-4acf-b67b-b86a07b7d8fa.png)

论文中在提及在池化、深监督等方面是和nnunet有些许不同的，是您手动修改了nnFormerPlansv2.1_plans_3D文件吗？还是我没有进行正确的预处理？

**Comment by 282857341** [comment]
我只使用了plans文件里的batch size和crop size，其他的关于nnunet自带的plans的参数都没有使用。
我修改plans的代码如下：
https://github.com/282857341/nnFormer/blob/02981008c99c7be6fad004f6a0b9e237d6985707/nnformer/run/default_configuration.py#L54-L59

**Comment by lzy-whut** [comment]
> 我只使用了plans文件里的batch size和crop size，其他的关于nnunet自带的plans的参数都没有使用。 我修改plans的代码如下：
> 
> https://github.com/282857341/nnFormer/blob/02981008c99c7be6fad004f6a0b9e237d6985707/nnformer/run/default_configuration.py#L54-L59

明白了，是因为我的数据集文件夹命名和您的不一致导致此处未进行判断，因此未修改plan文件。


此外，我还有一个疑问，您在训练后是使用predict_simple.py文件对验证集进行了预测吗？最终结果取得是这个结果吗？这和nnuent训练结束时validation_raw_postprocessed文件夹中summary.json的结果有什么区别吗？

**Comment by 282857341** [comment]
我没有使用predict_simple.py对验证集进行预测，而是训练结束后就用predict_simple.py对测试集进行预测（除开synapse数据验证集就是测试集），最终取得结果也是测试集上的结果。

然后针对validation_raw_postprocessed这个文件夹，我不是很清楚，对这一方面没有深入了解。不过我代码里是把对验证集预测的部分给注释掉了，如下：
https://github.com/282857341/nnFormer/blob/02981008c99c7be6fad004f6a0b9e237d6985707/nnformer/run/run_training.py#L203-L206

**Comment by lzy-whut** [comment]
> 

好的，我明白了。
十分感谢您的及时回复，祝您科研顺利。

**Comment by 282857341** [comment]
：） 小事
