### ISSUE TITLE
Can't find the global self-attention code.

### ISSUE THREAD

**Issue by GYDDHPY** [282857341/nnFormer#78]
Hi,I didn't find the global attention module mentioned in the nnFormer article.

According to the article,there are some global self-attention module used in the bottle neck as the computation cost is similiar to the local attention module.But I didn't find the global attention module.The code seems always use the local SWIN transformer block to encode the feature.

Could please tell me which part is relevant to the global self-attention block?

**Comment by 282857341** [comment]
We set the window size for different stages of the network to reach the goal of the global self-attention.
https://github.com/282857341/nnFormer/blob/78ab7e3f79235b828c74ff1eb058e42bdae16e0b/nnformer/training/network_training/nnFormerTrainerV2_nnformer_synapse.py#L72

**Comment by GYDDHPY** [comment]
Thank you for your attention.

I just notice the setting.
