### ISSUE TITLE
Typo in WindowAttention?

### ISSUE THREAD

**Issue by parap1uie-s** [282857341/nnFormer#8]
As described below,

https://github.com/282857341/nnFormer/blob/3aea3001a918ea2de12ec28cf9043989e99cd8f1/nnformer/network_architecture/Swin_Unet_l_gelunorm.py#L111-L112

should 
```
relative_coords[:, :, 0] *= 3 * self.window_size[1] - 1
```
to be 
```
relative_coords[:, :, 0] *= 3 * self.window_size[0] - 1
```
?

**Comment by 282857341** [comment]
Thanks for feedback! 

The purpose of the multiplication sign here is to distinguish the offset of the three dimensions. The specific multiplication is not important, as long as the three dimensions can be distinguished. So I chose to multiply by three and multiply the same number for two of the dimensions here.

And if window_size[0]==window_size[1], it will not play the role of distinguishing the dimensions here.

The way of our architecture may not be the optimal, we expect you find a better way.

**Comment by parap1uie-s** [comment]
> And if window_size[0]==window_size[1], it will not play the role of distinguishing the dimensions here.

Yes, it is equivalent when ```window_size[0]==window_size[1]```. However, it is misleading and not elegant enough.
