### ISSUE TITLE
About the plans.pkl file

### ISSUE THREAD

**Issue by hytim** [282857341/nnFormer#80]
When I use pickle.load() to read the 'plans.pkl' file, it returns a empty list. However, the file is not empty(21KB).
I do not know what the problem is. 
Thanks very much if you can help me.

**Comment by 282857341** [comment]
Can you provide the complete error information for me？That's will be helpful for the problem.

**Comment by hytim** [comment]
> 
import pickle

with open('./swino_plans.pkl', 'rb') as fo:
    #dict_data = pickle.load(fo, encoding='bytes')
    dict_data = pickle.load(fo)
    print(dict_data)

I use the code above, and the print result is just [].

**Comment by hytim** [comment]
> Can you provide the complete error information for me？That's will be helpful for the problem.

The code runs but I get an empty output.

**Comment by hytim** [comment]
> Can you provide the complete error information for me？That's will be helpful for the problem.
By the way, I wonder if the results in your paper was trained by 13 classes.

**Comment by 282857341** [comment]
> > 
> 
> import pickle
> 
> with open('./swino_plans.pkl', 'rb') as fo: #dict_data = pickle.load(fo, encoding='bytes') dict_data = pickle.load(fo) print(dict_data)
> 
> I use the code above, and the print result is just [].

I use the code above, and get the results correctly. Maybe there exists some other problems

**Comment by 282857341** [comment]
> > Can you provide the complete error information for me？That's will be helpful for the problem.
> > By the way, I wonder if the results in your paper was trained by 13 classes.

Yes

**Comment by hytim** [comment]
> 



> > > 
> > 
> > 
> > import pickle
> > with open('./swino_plans.pkl', 'rb') as fo: #dict_data = pickle.load(fo, encoding='bytes') dict_data = pickle.load(fo) print(dict_data)
> > I use the code above, and the print result is just [].
> 
> I use the code above, and get the results correctly. Maybe there exists some other problems

I wil check if there are other problems.
Thanks for you reply.
