### ISSUE TITLE
How to export segmentations?

### ISSUE THREAD

**Issue by Chadkowski** [282857341/nnFormer#85]
As title says, how to export segmentations? I've tried "predict" as is stated in the inference_train.sh but I keep getting this error:

nnformer_synapse
using model stored in  /home/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_nnformer_synapse__nnFormerPlansv2.1
###############################################
I am running the following nnFormer: 3d_fullres
My trainer class is:  <class 'nnformer.training.network_training.nnFormerTrainerV2_nnformer_synapse.nnFormerTrainerV2_nnformer_synapse'>
For that I will be using the following configuration:
num_classes:  13
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 80, 160, 160]), 'median_patient_size_in_voxels': array([138, 240, 240]), 'current_spacing': array([3.21640606, 1.61430703, 1.61430703]), 'original_spacing': array([3.        , 0.75781244, 0.75781244]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 4, 'num_pool_per_axis': [3, 5, 5], 'patch_size': array([ 64, 128, 128]), 'median_patient_size_in_voxels': array([148, 512, 512]), 'current_spacing': array([3.        , 0.75781244, 0.75781244]), 'original_spacing': array([3.        , 0.75781244, 0.75781244]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/nnFormer/DATASET/nnFormer_preprocessed/Task002_Synapse/nnFormerData_plans_v2.1
###############################################
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['im']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
found 20 unexpected remaining files in the folder. Here are some examples: ['img0073.nii.gz' 'img0063.nii.gz' 'img0072.nii.gz' 'img0066.nii.gz'
 'img0074.nii.gz' 'img0066.nii.gz' 'img0076.nii.gz' 'img0067.nii.gz'
 'img0075.nii.gz' 'img0079.nii.gz']
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, [0]
2022-07-26 07:53:35.074604: Using dummy2d data augmentation
[0.57142857 0.28571429 0.14285714]
/home/dawidr/.local/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
I am using the pre_train weight!!
using the following model files:  ['/home/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_nnformer_synapse__nnFormerPlansv2.1/fold_0/model_best.model']
starting preprocessing generator
starting prediction...
preprocessing inferTs/nnformer_synapse/im.nii.gz
using preprocessor GenericPreprocessor
error in ['imagesTs/img0061.nii.gz', 'imagesTs/img0062.nii.gz', 'imagesTs/img0063.nii.gz', 'imagesTs/img0064.nii.gz', 'imagesTs/img0065.nii.gz', 'imagesTs/img0066.nii.gz', 'imagesTs/img0067.nii.gz', 'imagesTs/img0068.nii.gz', 'imagesTs/img0069.nii.gz', 'imagesTs/img0070.nii.gz', 'imagesTs/img0071.nii.gz', 'imagesTs/img0072.nii.gz', 'imagesTs/img0073.nii.gz', 'imagesTs/img0074.nii.gz', 'imagesTs/img0075.nii.gz', 'imagesTs/img0076.nii.gz', 'imagesTs/img0077.nii.gz', 'imagesTs/img0078.nii.gz', 'imagesTs/img0079.nii.gz', 'imagesTs/img0080.nii.gz']
all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 138 and the array at index 1 has size 90
This worker has ended successfully, no errors to report
inference done. Now waiting for the segmentation export to finish...
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is /home/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_nnformer_synapse__nnFormerPlansv2.1
loading success...
[]
[]
/home/dawidr/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dawidr/.local/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
done

**Comment by sydat2701** [comment]
Hello, I got the same problem when I do the inference after training time, which make all the results Nan. Did you solve it?
