### ISSUE TITLE
preprocess data

### ISSUE THREAD

**Issue by hoolizou** [282857341/nnFormer#9]
Hi!Thank you great works!
Anyway, can share the preprocess data script of dataset, specially, about the Synapse multi-organ CT dataset？please.

**Comment by 282857341** [comment]
We use nnunet‘s code to preprocess the data
```
nnFormer_plan_and_preprocess -t 1
```
And before you start preprocessing the data, you should organize the raw data as we said in the README.MD

**Comment by hoolizou** [comment]
Well. thank you. lastly, I want konw how to deal with image normalization in Synapse multi-organ CT dataset.
