### ISSUE TITLE
在Synapse多器官分割数据集上

### ISSUE THREAD

**Issue by AustinYuAo** [282857341/nnFormer#96]
你好，多有打扰！论文中在Synapse多器官分割数据集上是对8器官的进行了评估，数据集不是包含13器官标签嘛？那训练模型的时候是对数据集处理删除5个标签了吗？还是在含有13标签的数据集上训练模型，然后对模型在8个器官上进行评估呀？

**Comment by 282857341** [comment]
在含有13标签的数据集上训练模型，然后对模型在8个器官上进行评估
